/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectosemestral;

import javax.swing.JOptionPane;

/**
 *
 * @author Hilda
 */
public class Ventana3 extends javax.swing.JFrame {
    GestionActividades g=new GestionActividades();
    Intermediario i=new Intermediario();
    /**
     * Creates new form Ventana3
     */
    public Ventana3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jRadioButton4 = new javax.swing.JRadioButton();
        texto4 = new javax.swing.JLabel();
        buttonGroup6 = new javax.swing.ButtonGroup();
        Titulo1 = new javax.swing.JLabel();
        texto1 = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();
        texto3 = new javax.swing.JLabel();
        texto5 = new javax.swing.JLabel();
        texto6 = new javax.swing.JLabel();
        texto7 = new javax.swing.JLabel();
        texto8 = new javax.swing.JLabel();
        Libro = new javax.swing.JToggleButton();
        Siguiente = new javax.swing.JButton();
        Bebida = new javax.swing.JToggleButton();
        Musica = new javax.swing.JToggleButton();
        Caminata = new javax.swing.JToggleButton();
        Instrumento = new javax.swing.JToggleButton();
        Datos = new javax.swing.JLabel();

        Titulo.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(51, 153, 255));
        Titulo.setText("StressFree");

        texto4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        texto4.setForeground(new java.awt.Color(51, 153, 255));
        texto4.setText("Leer un parrafo de un libro al azar de nuestro sistema de archivos");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(51, 153, 255));
        Titulo1.setText("StressFree");

        texto1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        texto1.setForeground(new java.awt.Color(51, 153, 255));
        texto1.setText("Ahora debe elegir que le gustaría hacer en su tiempo de descanso.");

        texto2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        texto2.setForeground(new java.awt.Color(51, 153, 255));
        texto2.setText("Marque las opciones correspondientes según sus gustos.");

        texto3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        texto3.setForeground(new java.awt.Color(51, 153, 255));
        texto3.setText("Leer un parrafo de un libro al azar de nuestro sistema de archivos");

        texto5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        texto5.setForeground(new java.awt.Color(51, 153, 255));
        texto5.setText("Escuchar musica relajante(Si trabaja con mas gente se recomiendan audifonos)");

        texto6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        texto6.setForeground(new java.awt.Color(51, 153, 255));
        texto6.setText("Beber una bebida caliente (puede acompañarla con un cigarro si usted fuma)");

        texto7.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        texto7.setForeground(new java.awt.Color(51, 153, 255));
        texto7.setText("Salir a caminar por su sector(no recomendable si esta lloviendo)");

        texto8.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        texto8.setForeground(new java.awt.Color(51, 153, 255));
        texto8.setText("Tocar algún instrumento de su gusto(SOLO APLICABLE TRABAJANDO EN CASA)");

        Libro.setText("click aqui");
        Libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibroActionPerformed(evt);
            }
        });

        Siguiente.setText("Siguiente");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });

        Bebida.setText("click aqui");
        Bebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BebidaActionPerformed(evt);
            }
        });

        Musica.setText("click aqui");
        Musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusicaActionPerformed(evt);
            }
        });

        Caminata.setText("click aqui");
        Caminata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaminataActionPerformed(evt);
            }
        });

        Instrumento.setText("click aqui");
        Instrumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstrumentoActionPerformed(evt);
            }
        });

        Datos.setText("Catalina Aguayo, Felipe Vásquez, Segundo Semestre 2016");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(texto1)
                            .addGap(188, 188, 188))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(texto8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(texto5)
                                    .addGap(14, 14, 14)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Musica)
                                .addComponent(Instrumento))
                            .addGap(28, 28, 28))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(texto7)
                            .addContainerGap()))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Caminata)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(texto6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Bebida))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(texto3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Libro))))
                        .addGap(29, 29, 29))))
            .addGroup(layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(Titulo1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(texto2))
                    .addComponent(Datos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(Titulo1)
                .addGap(39, 39, 39)
                .addComponent(texto1)
                .addGap(18, 18, 18)
                .addComponent(texto2)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto3)
                    .addComponent(Libro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto5)
                    .addComponent(Musica))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bebida)
                    .addComponent(texto6))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto7)
                    .addComponent(Caminata))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto8)
                    .addComponent(Instrumento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(Siguiente)
                .addGap(11, 11, 11)
                .addComponent(Datos))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LibroActionPerformed

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        
        setVisible(false);
        i.VentanaYGuardar(Libro.isSelected(), Caminata.isSelected(),Bebida.isSelected(),Instrumento.isSelected(),Musica.isSelected());
    }//GEN-LAST:event_SiguienteActionPerformed

    private void BebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BebidaActionPerformed

    private void MusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MusicaActionPerformed

    private void CaminataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaminataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaminataActionPerformed

    private void InstrumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstrumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InstrumentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Bebida;
    private javax.swing.JToggleButton Caminata;
    private javax.swing.JLabel Datos;
    private javax.swing.JToggleButton Instrumento;
    private javax.swing.JToggleButton Libro;
    private javax.swing.JToggleButton Musica;
    private javax.swing.JButton Siguiente;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Titulo1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto3;
    private javax.swing.JLabel texto4;
    private javax.swing.JLabel texto5;
    private javax.swing.JLabel texto6;
    private javax.swing.JLabel texto7;
    private javax.swing.JLabel texto8;
    // End of variables declaration//GEN-END:variables
}
