/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectosemestral;

import javax.swing.JOptionPane;

/**
 *
 * @author Hilda
 */
public class Ventana3 extends javax.swing.JFrame {
    GestionActividades g=new GestionActividades();
    Intermediario i=new Intermediario();
    /**
     * Creates new form Ventana3
     */
    public Ventana3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jRadioButton4 = new javax.swing.JRadioButton();
        texto4 = new javax.swing.JLabel();
        buttonGroup6 = new javax.swing.ButtonGroup();
        Titulo1 = new javax.swing.JLabel();
        texto1 = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();
        texto3 = new javax.swing.JLabel();
        texto5 = new javax.swing.JLabel();
        texto6 = new javax.swing.JLabel();
        texto7 = new javax.swing.JLabel();
        texto8 = new javax.swing.JLabel();
        Libro = new javax.swing.JToggleButton();
        Siguiente = new javax.swing.JButton();
        Bebida = new javax.swing.JToggleButton();
        Musica = new javax.swing.JToggleButton();
        Caminata = new javax.swing.JToggleButton();
        Instrumento = new javax.swing.JToggleButton();
        Datos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        Titulo.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(51, 153, 255));
        Titulo.setText("StressFree");

        texto4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        texto4.setForeground(new java.awt.Color(51, 153, 255));
        texto4.setText("Leer un parrafo de un libro al azar de nuestro sistema de archivos");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));

        Titulo1.setFont(new java.awt.Font("American Typewriter", 1, 36)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(0, 102, 102));
        Titulo1.setText("StressFree");

        texto1.setFont(new java.awt.Font("AppleGothic", 0, 24)); // NOI18N
        texto1.setForeground(new java.awt.Color(0, 153, 153));
        texto1.setText("Ahora debe elegir que le gustaría hacer en su tiempo de descanso");

        texto2.setFont(new java.awt.Font("AppleGothic", 1, 18)); // NOI18N
        texto2.setForeground(new java.awt.Color(0, 153, 153));
        texto2.setText("Marque las opciones correspondientes según sus gustos");

        texto3.setFont(new java.awt.Font("American Typewriter", 0, 16)); // NOI18N
        texto3.setForeground(new java.awt.Color(0, 153, 51));
        texto3.setText("Leer un parrafo de un libro al azar de nuestro sistema de archivos");

        texto5.setFont(new java.awt.Font("American Typewriter", 0, 16)); // NOI18N
        texto5.setForeground(new java.awt.Color(0, 153, 51));
        texto5.setText("Escuchar musica relajante");

        texto6.setFont(new java.awt.Font("American Typewriter", 0, 16)); // NOI18N
        texto6.setForeground(new java.awt.Color(0, 153, 51));
        texto6.setText("Beber una bebida caliente (puede acompañarla con un cigarro si usted fuma)");

        texto7.setFont(new java.awt.Font("American Typewriter", 0, 16)); // NOI18N
        texto7.setForeground(new java.awt.Color(0, 153, 51));
        texto7.setText("Salir a caminar por su sector(no recomendable si esta lloviendo)");

        texto8.setFont(new java.awt.Font("American Typewriter", 0, 16)); // NOI18N
        texto8.setForeground(new java.awt.Color(0, 153, 51));
        texto8.setText("Tocar algún instrumento de su gusto(SOLO APLICABLE TRABAJANDO EN CASA)");

        Libro.setFont(new java.awt.Font("American Typewriter", 1, 14)); // NOI18N
        Libro.setForeground(new java.awt.Color(0, 51, 51));
        Libro.setText("click aquí");
        Libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibroActionPerformed(evt);
            }
        });

        Siguiente.setFont(new java.awt.Font("American Typewriter", 0, 18)); // NOI18N
        Siguiente.setForeground(new java.awt.Color(0, 51, 51));
        Siguiente.setText("Siguiente");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });

        Bebida.setFont(new java.awt.Font("American Typewriter", 1, 14)); // NOI18N
        Bebida.setForeground(new java.awt.Color(0, 51, 51));
        Bebida.setText("click aqui");
        Bebida.setActionCommand("click aquí");
        Bebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BebidaActionPerformed(evt);
            }
        });

        Musica.setFont(new java.awt.Font("American Typewriter", 1, 14)); // NOI18N
        Musica.setForeground(new java.awt.Color(0, 51, 51));
        Musica.setText("click aquí");
        Musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusicaActionPerformed(evt);
            }
        });

        Caminata.setFont(new java.awt.Font("American Typewriter", 1, 14)); // NOI18N
        Caminata.setForeground(new java.awt.Color(0, 51, 51));
        Caminata.setText("click aquí");
        Caminata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaminataActionPerformed(evt);
            }
        });

        Instrumento.setFont(new java.awt.Font("American Typewriter", 1, 14)); // NOI18N
        Instrumento.setForeground(new java.awt.Color(0, 51, 61));
        Instrumento.setText("click aquí");
        Instrumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstrumentoActionPerformed(evt);
            }
        });

        Datos.setText("Catalina Aguayo, Felipe Vásquez, Segundo Semestre 2016");

        jLabel1.setFont(new java.awt.Font("American Typewriter", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("(Si trabaja con mas gente se recomiendan audifonos)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Datos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(texto8)
                    .addComponent(texto5)
                    .addComponent(jLabel1)
                    .addComponent(texto6)
                    .addComponent(texto7)
                    .addComponent(texto3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bebida)
                            .addComponent(Caminata)
                            .addComponent(Musica)
                            .addComponent(Libro))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Instrumento)
                        .addContainerGap(20, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(texto1)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(texto2)
                        .addGap(222, 222, 222))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(Titulo1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(Siguiente)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(Titulo1)
                .addGap(18, 18, 18)
                .addComponent(texto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(texto2)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texto3)
                            .addComponent(Instrumento))
                        .addGap(22, 22, 22)
                        .addComponent(texto5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(Libro))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto6)
                    .addComponent(Musica))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texto8)
                            .addComponent(Caminata))
                        .addGap(25, 25, 25)
                        .addComponent(Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(Datos))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bebida)
                            .addComponent(texto7))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LibroActionPerformed

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        
        setVisible(false);
        i.guardar(Libro.isSelected(), Caminata.isSelected(),Bebida.isSelected(),Instrumento.isSelected(),Musica.isSelected());
        i.ventana4();
    }//GEN-LAST:event_SiguienteActionPerformed

    private void BebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BebidaActionPerformed

    private void MusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MusicaActionPerformed

    private void CaminataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaminataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaminataActionPerformed

    private void InstrumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstrumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InstrumentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Bebida;
    private javax.swing.JToggleButton Caminata;
    private javax.swing.JLabel Datos;
    private javax.swing.JToggleButton Instrumento;
    private javax.swing.JToggleButton Libro;
    private javax.swing.JToggleButton Musica;
    private javax.swing.JButton Siguiente;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Titulo1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto3;
    private javax.swing.JLabel texto4;
    private javax.swing.JLabel texto5;
    private javax.swing.JLabel texto6;
    private javax.swing.JLabel texto7;
    private javax.swing.JLabel texto8;
    // End of variables declaration//GEN-END:variables
}
